Feature/update starter pack
AgePartnership/oleg-brand-kit pull request #102
Opened 2023-11-01 11:38 UTC by kimoshinowo98

Ticket: https://webjobs.agepartnership.co.uk/desk/tickets/6673838/messages

Changes:
- Update oleg-starter-pack to scoped version

Checks:
- Non-malicious

2024-01-09 10:44 UTC, ryanfitton-ap commented on ap-plus/config/_space.scss
> +$column-gap: $space * 0.5
Using a divide is deprecated, so changed to multiply by 0.5 which returns the same result: 8px

2024-01-09 10:44 UTC, ryanfitton-ap commented on config/_config.space.scss
> +$column-gap: $space * 0.5
As above, Using a divide is deprecated, so changed to multiply by 0.5 which returns the same result: 8px

2024-01-09 10:44 UTC, ryanfitton-ap commented on rebuild/config/_base-unit.scss
> +$base-unit: 8px !default; // Default AP space variable
Adding default so this will only be applied if there is no `$base-unit` variable set previously

2024-01-09 10:44 UTC, ryanfitton-ap commented on test.scss
> +$space: 16px; //Already included in `config/_config.space.scss`, but we can overwrite and use this value instead
Adding default so this will only be applied if there is no `$space` variable set previously

2024-01-09 10:44 UTC, ryanfitton-ap commented on test.scss
> +}
Adding test for default starter pack

2024-01-09 10:44 UTC, ryanfitton-ap commented on test.scss
> +}
Add test for Rebuild starterpack config

2024-01-09 10:44 UTC, ryanfitton-ap commented on wealthy-senior-execs/config/_space.scss
> +$column-gap: $space * 0.5
As above, Using a divide is deprecated, so changed to multiply by 0.5 which returns the same result: 8px

2024-06-04 12:30 UTC, ryanfitton-ap requested changes

2024-06-04 12:30 UTC, ryanfitton-ap commented on package.json
> +        "@agepartnership/oleg-starter-pack": "^5.0.1"
Think we should be able to upgrade this to the latest version? `v5.1.1`

2024-06-04 12:30 UTC, ryanfitton-ap commented on test.scss
Can we remove this test file?

2024-06-04 14:25 UTC, kimoshinowo98 commented on test.scss
@ryanfitton-ap Oh I'd left in as I thought we wanted to keep - did you just add as a temporary test to see the changes?

2024-10-16 07:59 UTC, ryanfitton-ap requested changes
FIne to remove the test file. Sorry, never actually submitted this review, it was still a draft.

2024-10-18 07:57 UTC, ryanfitton-ap commented on test.scss
@kimoshinowo98 I thought I added this test file, but it was a pre-existing file: https://github.com/AgePartnership/oleg-brand-kit/blob/develop/test.scss

Probably best to add it back, then we can see if any styles fail in future PR, that way we will know before merging and using in other sites.

2024-10-18 07:58 UTC, ryanfitton-ap requested changes
Let's re-add the test.scss file. I thought I added it to test the !default, but it was a pre-existing file instead https://github.com/AgePartnership/oleg-brand-kit/blob/develop/test.scss

2024-10-22 09:48 UTC, ryanfitton-ap requested changes
@kimoshinowo98 Few changes, but looks good.

2024-10-22 09:48 UTC, ryanfitton-ap commented on test.scss
> +$space: 16px; //Already included in `config/_config.space.scss`, but we can overwrite and use this value instead
Should be able to remove this, sounds like it was testing

2024-10-22 09:48 UTC, ryanfitton-ap commented on test.scss
> +}
Remove this test too

2024-10-22 09:48 UTC, ryanfitton-ap commented on test.scss
> +*/
And remove this

2024-10-22 14:42 UTC, ryanfitton-ap requested changes

2024-10-22 14:42 UTC, ryanfitton-ap commented on test.scss
> -$space: 16px; //Already included in `config/_config.space.scss`, but we can overwrite and use this value instead
Sorry this line is causing a Travis error, lets add this single line back.

2024-10-22 15:05 UTC, ryanfitton-ap approved these changes

2024-10-23 12:22 UTC, merged

2024-10-23 12:24 UTC, kimoshinowo98 commented
Published in: @agepartnership/oleg-brand-kit@4.2.0