Feature/add eh refresh colours
AgePartnership/oleg-brand-kit pull request #29
Opened 2020-11-19 09:17 UTC by marymooney

Ticket: https://webjobs.agepartnership.co.uk/desk/tickets/5497817/messages

Changes: Adds colours & typography required for the Eamonn Holmes email refresh. I wasn't 100% sure about the approach to colours. Didn't seem to make sense having grey-1 and grey-2 so I have removed but I imagine when we start on the site rebuild these will be re-jigged / added. 

Checks: 
- [ ] Meets code standards / guidelines
- [ ] Malicious code

2020-11-19 16:49 UTC, beccadawson approved these changes
Approving as sensible and non-malicious, I'm just not sure how we know the font sizes / line heights as they've not specified afaict?

2020-11-20 12:07 UTC, beccadawson requested changes

2020-11-20 12:07 UTC, beccadawson commented on package.json
> +  "version": "2.0.9",
Minor version is the middle number! `Major.Minor.Patch`

2020-11-20 16:12 UTC, beccadawson approved these changes

2020-11-23 08:47 UTC, marymooney commented
@beccadawson 
> Approving as sensible and non-malicious, I'm just not sure how we know the font sizes / line heights as they've not specified afaict?

Do you want me to ask ATP? As they haven't specified I'd gone with basing it off our existing font sizes/line heights. I thought font sizes was one of the things we weren't pushing them too hard on but maybe I misunderstood!

2020-11-23 09:30 UTC, beccadawson commented
> @beccadawson
> 
> > Approving as sensible and non-malicious, I'm just not sure how we know the font sizes / line heights as they've not specified afaict?
> 
> Do you want me to ask ATP? As they haven't specified I'd gone with basing it off our existing font sizes/line heights. I thought font sizes was one of the things we weren't pushing them too hard on but maybe I misunderstood!

No its fine, I just wasn't sure!

2020-11-23 14:09 UTC, merged