Use migrator to stop use of / for division
AgePartnership/oleg-brand-kit pull request #51
Opened 2021-10-12 12:28 UTC by kimoshinowo98

Ticket: https://webjobs.agepartnership.co.uk/desk/tickets/5687300/messages

Changes:
- Use sass-migrator to change division slashes to multiplications or to use math.div()

Checks:
- Non-malicious
- Sense

2024-01-10 11:40 UTC, beccadawson requested changes

2024-01-10 11:40 UTC, beccadawson commented on config/_config.space.scss
> +$column-gap: $space*0.5;
Just for consistency can we add spaces round the *

2024-01-10 12:11 UTC, beccadawson approved these changes

2024-01-10 12:11 UTC, beccadawson requested changes
Just spotted travis failing

2024-01-11 09:48 UTC, kimoshinowo98 commented
Weird stuff is happening with this so I think it's worth waiting for https://github.com/AgePartnership/oleg-brand-kit/pull/96 to be merged first and seeing if that helps

2024-02-13 11:54 UTC, beccadawson approved these changes

2024-02-13 14:47 UTC, merged